name: who_app
description: COVID-19 app

# This app is published as a mobile app, not to pub.dev.
publish_to: none

# Prior to a production release, this version is the
# next expected version, and the `-git` suffix is a
# pre-release indicator.
# https://dart.dev/tools/pub/pubspec#version
version: 0.16.0+27-git

repository: https://github.com/WorldHealthOrganization/app

issue_tracker: https://github.com/WorldHealthOrganization/app/issues

# If the flutter sdk version in pubspec.lock changes,
# you must update /.github/workflows/flutter-*.yml to use same min Flutter version

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.1 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: 2.1.0
  connectivity: ^2.0.0
  cupertino_icons: ^0.1.3
  expressions: 0.1.5
  firebase_analytics: ^6.0.0
  firebase_core: ^0.5.2
  firebase_crashlytics: ^0.2.3
  firebase_messaging: ^8.0.0-dev.8
  fixnum: ^0.10.11
  fl_chart: ^0.8.7
  # TODO: upgrade to ^1.4.0, breaking API change
  flutter_cache_manager: 1.1.3
  flutter_html: ^0.11.1
  flutter_mobx: ^1.1.0+2
  flutter_svg: ^0.18.0
  font_awesome_flutter: ^8.8.1
  http: ^0.12.0+3
  mobx: ^1.2.1+2
  notification_permissions: ^0.4.4
  observer_provider: 0.0.1+2
  package_info: ">=0.4.0+16 <2.0.0"
  page_view_indicator: ^2.0.4
  path_drawing: ^0.4.1
  path_provider: ^1.6.5
  protobuf: ^1.0.1
  provider: ^4.3.2
  # TODO: upgrade to ^0.6.5+2, build warning treated as error
  share: 0.6.3+6
  shared_preferences: ^0.5.6
  url_launcher: ^5.4.2
  uuid: 2.0.4
  visibility_detector: ^0.1.4
  yaml: ^2.2.0

  intl: ^0.16.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  build_runner: ^1.10.1
  mobx_codegen: ^1.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/animations/
    - assets/onboarding/
    - assets/content_bundles/

flutter_intl:
  enabled: true
